openapi: 3.0.0
info:
  title: NutriHelp API
  version: 1.0.0
servers:
  - url: http://localhost/api
paths:
  /contactus:
    post:
      summary: Contact us
      description: Receives a contact request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRequest'
      responses:
        '201':
          description: Data received successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request - missing required fields
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /signup:
    post:
      summary: User signup
      description: Registers a new user with a username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsernamePassword'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request - either missing username/password or user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /login:
    post:
      summary: User login
      description: Authenticates user and returns a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsernamePassword'
      responses:
        '200':
          description: Login successful, JWT token returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTToken'
        '400':
          description: Username and password are required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /appointments:
    post:
      summary: Save appointment data
      description: Receives a user ID, date, time, and description, and saves the appointment data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request - missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Retrieve all appointment data
      description: Returns a JSON array containing all appointments
      responses:
        '200':
          description: Appointments fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /fooddata/dietaryrequirements:
    get:
      summary: Get dietary requirements
      description: Retrieves a list of dietary requirements
      responses:
        '200':
          description: List of dietary requirements
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDNamePair'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /fooddata/cuisines:
    get:
      summary: Get cuisines
      description: Retrieves a list of cuisines
      responses:
        '200':
          description: List of cuisines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDNamePair'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /fooddata/allergies:
    get:
      summary: Get allergies
      description: Retrieves a list of allergies
      responses:
        '200':
          description: List of allergies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDNamePair'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /fooddata/ingredients:
    get:
      summary: Get ingredients
      description: Retrieves a list of ingredients (name and ID only)
      responses:
        '200':
          description: List of ingredients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDNamePair'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /fooddata/cookingmethods:
    get:
      summary: Get cooking methods
      description: Retrieves a list of cooking methods
      responses:
        '200':
          description: List of cooking methods
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDNamePair'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /fooddata/spicelevels:
    get:
      summary: Get spice levels
      description: Retrieves a list of spice levels
      responses:
        '200':
          description: List of spice levels
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDNamePair'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /fooddata/healthconditions:
    get:
      summary: Get health conditions
      description: Retrieves a list of health conditions
      responses:
        '200':
          description: List of health conditions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDNamePair'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user/preferences:
    get:
      summary: Get user preferences
      description: Retrieves a list of user preferences
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: List of user preferences
          content:
            application/json:
              schema:
                type: object
                properties:
                  dietary_requirements:
                    type: array
                    items:
                      $ref: '#/components/schemas/IDNamePair'
                  allergies:
                    type: array
                    items:
                      $ref: '#/components/schemas/IDNamePair'
                  cuisines:
                    type: array
                    items:
                      $ref: '#/components/schemas/IDNamePair'
                  dislikes:
                    type: array
                    items:
                      $ref: '#/components/schemas/IDNamePair'
                  health_conditions:
                    type: array
                    items:
                      $ref: '#/components/schemas/IDNamePair'
                  spice_levels:
                    type: array
                    items:
                      $ref: '#/components/schemas/IDNamePair'
                  cooking_methods:
                    type: array
                    items:
                      $ref: '#/components/schemas/IDNamePair'
              examples:
                userPreferences:
                  value:
                    dietary_requirements:
                      - id: 1
                        name: "Vegetarian"
                    allergies:
                      - id: 1
                        name: "Peanuts"
                    cuisines:
                      - id: 2
                        name: "French"
                      - id: 5
                        name: "Italian"
                    dislikes:
                      - id: 4
                        name: "Chicken Thigh Fillets"
                    health_conditions: [ ]
                    spice_levels:
                      - id: 1
                        name: "Mild"
                      - id: 2
                        name: "Medium"
                    cooking_methods:
                      - id: 1
                        name: "Bake"
                      - id: 4
                        name: "Grill"
        '400':
          description: User ID is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User preferences not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update user preferences
      description: Updates the user's preferences
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dietary_requirements:
                  type: array
                  items:
                    type: integer
                allergies:
                  type: array
                  items:
                    type: integer
                cuisines:
                  type: array
                  items:
                    type: integer
                dislikes:
                  type: array
                  items:
                    type: integer
                health_conditions:
                  type: array
                  items:
                    type: integer
                spice_levels:
                  type: array
                  items:
                    type: integer
                cooking_methods:
                  type: array
                  items:
                    type: integer
            example:
              dietary_requirements: [ 1, 2, 4 ]
              allergies: [ 1 ]
              cuisines: [ 2, 5 ]
              dislikes: [ 4 ]
              health_conditions: [ ]
              spice_levels: [ 1, 2 ]
              cooking_methods: [ 1, 4, 5 ]
      responses:
        '204':
          description: User preferences updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: User IS is required or Request body is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UsernamePassword:
      type: object
      properties:
        username:
          type: string
          example: user123
        password:
          type: string
          format: password
          example: pass123
      required:
        - username
        - password
    JWTToken:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    ContactRequest:
      type: object
      properties:
        name:
          type: string
          description: The user's name
          example: Jane Doe
        email:
          type: string
          format: email
          description: The user's email address
          example: jane.doe@example.com
        message:
          type: string
          description: The user's message
          example: Hello, I have a question about...
      required:
        - name
        - email
        - message
    IDNamePair:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: Vegetarian
    Appointment:
      type: object
      properties:
        userId:
          type: integer
        date:
          type: string
          format: date-time
        time:
          type: string
        description:
          type: string
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: Data received successfully!
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Internal server error