logging:
  file_output: false
  file_path: logs/scanner.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
plugins:
  jwt_configuration:
    config:
      check_env_files: true
      min_secret_length: 32
    enabled: true
  jwt_missing_protection:
    config:
      check_middleware: true
      check_routes: true
      exclude_paths:
      - /health
      - /api-docs
    enabled: true
  general_security:
    config:
      legacy_rules:
        enabled: true
        # default path relative to plugin dir; can be overridden with absolute path
        path: plugins/general_security/rules_v1.yaml
      # plugin-specific defaults
      allowlist_keys: ['TEST_SECRET', 'PLACEHOLDER', 'EXAMPLE_SECRET']
      exclude_paths: ['tests/', '__tests__/', 'fixtures/', 'node_modules/', '.venv/', 'venv/']
    enabled: true
  rls_missing_protection_disabled:
    config:
      rls_indicators:
      - auth.uid()
      - current_user
      - user_id
      - auth_user
      - rls
      - row level security
      sensitive_tables:
      - users
      - user_profiles
      - auth_logs
      - user_sessions
      - recipes
      - meal_plans
      - appointments
      - medical_predictions
      - user_feedback
      - notifications
    enabled: false
    severity_override: null
reports:
  formats:
    html:
      enabled: false
      include_css: true
      include_js: false
      template: default
    json:
      enabled: false
      include_metadata: true
      indent: 2
    text:
      enabled: false
      include_summary: true
      max_width: 120
  group_by_severity: true
  include_file_paths: true
  include_source_snippets: true
  include_timestamps: true
  max_snippet_lines: 5
  sort_by_severity: true
scanner:
  description: Specialized security scanner for NutriHelp project
  exclude_directories:
  - node_modules
  - .git
  - __pycache__
  - venv
  - .venv
  - dist
  - build
  - uploads
  - temp
  file_extensions:
  - .js
  - .ts
  - .py
  - .sql
  - .json
  - .yaml
  - .yml
  - .env
  name: NutriHelp Security Scanner V2.0
  # Engine-level global exclude paths (substring matches). These will be
  # injected into each plugin's exclude_paths so plugins and engine skip them.
  global_exclude_paths:
  - tests/
  - __tests__/
  - fixtures/
  - Vulnerability_Tool_V2/
  - reports/
  - scripts/
  - tools/
  - venv/
  - .venv/
  - node_modules/

  # New: internal scanner files filtering
  exclude_internal_scanner_files: true
  internal_paths:
  - routes/scanner.js
  - reports/
  - Vulnerability_Tool_V2/
  - Vulnerability_Tool/
  - scripts/
  scan_settings:
    max_file_size_mb: 50
    parallel_scanning: false
    timeout_seconds: 300
  version: 2.0.0
  # Recognize common global middleware names that indicate protection when used
  trusted_global_middlewares:
  - authenticateToken
  - useAuth
  - authorizeRoles
  - optionalAuth
  # Public paths that should not trigger JWT-missing alerts (prefix or exact match)
  public_paths:
  - /login
  - /signup
  - /health
  - /status
  - /mfa
  - /classify
  - /integrity-check
