name: CI (with npm cache)
 
on:
  push:
    branches: ["**"]
  pull_request:
 
env:
  NODE_VERSION: "20"
 
jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
 
      # 2. Setup Node.js with caching enabled
      - name: Setup Node with cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
 
      # 3. Install dependencies (reproducible and cache-friendly)
      - name: Install dependencies
        run: npm ci
 