---
    name: SecurityScanWorkflow
    
    on:
      push:
        branches: ["**"]
      pull_request:
        branches: ["**"]
    
    jobs:
      run-security-scan:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Set up Python environment
            uses: actions/setup-python@v3
            with:
              python-version: "3.x"
    
          - name: Install project dependencies
            run: |
              pip install --upgrade pip
              pip install -r requirements.txt
    
          - name: Execute Vulnerability Scanner
            run: python3 "Vulnerability_Tool/Vulnerability_Scanner_V1.3.py" > security_scan_report.txt
    
          - name: Save scan results as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: security-scan-report
              path: security_scan_report.txt
